flinkH: stubs

diff --git a/bin/flinkH b/bin/flinkH
--- a/bin/flinkH
+++ b/bin/flinkH
@@ -4,6 +4,7 @@
 import argparse, re, sys, os, json
 import yaml
 
+
 def main_dumpyaml(argv):
     ag = argparse.ArgumentParser()
     ag.add_argument('yaml', type=str, help='yaml file')
@@ -15,6 +16,7 @@ def main_dumpyaml(argv):
     else:
         with open(ag.output, 'w') as f:
             f.write(json.dumps(yaml.load(open(ag.yaml).read()), indent=2))
+
 
 def main_subst(argv):
     ag = argparse.ArgumentParser()
@@ -42,10 +44,162 @@ def main_subst(argv):
     with open(ag.target, 'w') as f:
         f.writelines(updated_lines)
 
+
+def _gen_debian(dst, meta):
+    '''
+test -n "$1" || (echo "missing dest dir"; false)
+dkGen_debian_changelog $1
+dkGen_debian_control $1
+dkGen_debian_copyright $1
+dkGen_debian_rules $1
+dkGen_debian_source_format $1
+    '''
+    pass
+
+def _gen_debian_changelog(dst, meta):
+    '''
+if ! test -r $1/debian/changelog; then
+		if test -z "$src"; then echo "DK: Please define 'src'"; false; fi
+		if test -z "$version"; then echo "DK: Please define 'version'"; false; fi
+		if test -z "$maintainer"; then echo "DK: Please define 'maintainer'"; false; fi
+		if test -n "$DK_VERBOSE"; then echo "DK: Generating $1/debian/changelog"; fi
+		mkdir -p $1/debian
+		cat > $1/debian/changelog <<EOF
+$src ($version) experimental; urgency=low
+
+  * Unofficial D**ian User Repo Release.
+  * Built on $(uname -a)
+
+ -- $maintainer  $(date -R)
+EOF
+	fi
+    '''
+    pass
+
+def _gen_debian_control(dst, meta):
+    '''
+    	if ! test -r $1/debian/control; then
+		if test -z "$src"; then echo "DK: Please define 'src'"; false; fi
+		if test -z "$section"; then echo "DK: Please define 'section'"; false; fi
+		if test -z "$stdver"; then stdver="4.3.0"; fi
+		if test -z "$compat"; then compat="11"; fi
+		if test -z "$maintainer"; then echo "DK: Please define 'maintainer'"; false; fi
+		if test -z "$description"; then echo "DK: Please define 'description'"; false; fi
+		if test -n "$DK_VERBOSE"; then echo "DK: Generating $1/debian/control"; fi
+		build_depends_="$build_depends"
+		if test -n "$(echo $dh_with | grep -o python)"; then
+			build_depends_="$build_depends_,dh-python";
+	   	fi
+		if test -n "$(echo $dh_with | grep -o python3)"; then
+			build_depends_="$build_depends_,python3-all,python3-all-dev";
+		fi
+		if test -n "$(echo $dh_with | grep -oP 'python[^3$]')"; then
+			build_depends_="$build_depends_,python-all,python-all-dev":
+	   	fi
+		mkdir -p $1/debian
+		cat > $1/debian/control <<EOF
+Source: $src
+Section: $section
+Homepage: $homepage
+Priority: optional
+Standards-Version: $stdver
+Maintainer: D**ian User Repo Contributors
+Uploaders: $maintainer
+Build-Depends: debhelper-compat (= $compat), $build_depends_
+
+Package: $src
+Architecture: any
+Multi-Arch: no
+Depends: \${shlibs:Depends}, \${python:Depends}, \${python3:Depends},
+  \${misc:Depends}, \${misc:Pre-Depends}, $depends
+Description: $description
+ $description
+EOF
+	fi
+    '''
+    pass
+
+
+def _gen_debian_copyright(dst, meta):
+    '''
+    	if ! test -r $1/debian/copyright; then
+		if test -z "$license"; then echo "DK: Please define 'license'"; false; fi
+		if test -n "$DK_VERBOSE"; then echo "DK: Generating $1/debian/copyright"; fi
+		mkdir -p $1/debian; echo "$license" > $1/debian/copyright
+	fi
+    '''
+    pass
+
+def _gen_debian_rules(dst, meta):
+    '''
+    	if ! test -r $1/debian/rules; then
+		if test -n "$DK_VERBOSE"; then echo "DK: Generating $1/debian/rules"; fi
+		if test -n "$dh_with"; then
+			dh_with_="--with $dh_with"
+		fi
+		if test -n "$dh_buildsystem"; then
+			dh_buildsystem_="-S$dh_buildsystem"
+		fi
+		mkdir -p $1/debian
+		cat > $1/debian/rules <<EOF
+#!/usr/bin/make -f
+%:
+	dh \$@ $dh_buildsystem_ $dh_with_
+EOF
+		if test -n "$dk_skip"; then
+			for item in $dk_skip; do
+				echo "" >> $1/debian/rules
+				echo "override_$item:" >> $1/debian/rules
+			done
+		fi
+		chmod +x $1/debian/rules
+	fi
+    '''
+    pass
+
+def _gen_debian_source_format(dst, meta):
+    '''
+    	if ! test -r $1/debian/source/format; then
+		if test -n "$DK_VERBOSE"; then echo "DK: Generating $1/debian/source/format"; fi
+		if test -z "$source_format"; then
+			mkdir -p $1/debian/source; echo "3.0 (native)" > $1/debian/source/format
+		else
+			mkdir -p $1/debian/source; echo "$source_format" > $1/debian/source/format
+		fi
+	fi
+    '''
+    pass
+
+def main_prep_source(argv):
+    '''
+    	if test -d $src; then
+		echo "DK: Could you please remove $src/ directory first?"
+		exit 1
+	fi
+	mkdir $src;
+	if test $(tar tf ${src}_${version}.tar.* | awk -F/ '{m=9} NF<m{m=NF} END{print m}') = 1; then
+		tar xf ${src}_${version}.tar.* -C $src/
+	else
+		tar xf ${src}_${version}.tar.* --strip-components=1 -C $src/
+	fi
+    '''
+    pass
+
+def main_debianize(argv):
+    '''
+    	dkGenerate $src
+	dkSubst_ ${0%.sh}.hft
+	hft -v -u ${0%.sh}.hft -d $src/ -F
+    '''
+    pass
+
+
 if __name__ == '__main__':
     if len(sys.argv) < 2:
         print(f'Usage: {__file__} <ACTION> [<ARGUMENTS>]')
-        print('Actions: dumpyaml')
+        print('Actions:')
+        print('  ', [k.replace('main_', '')
+            for (k, v) in locals().items() if k.startswith('main')])
         exit(0)
     # NOTE: I don't like the subparsers (argparse).
     eval(f'main_{sys.argv[1]}')(sys.argv[2:])
