lib: update duprkit and install it

diff --git a/lib/duprkit b/lib/duprkit
--- a/lib/duprkit
+++ b/lib/duprkit
@@ -1,11 +1,63 @@
 #!/bin/sh
 set -e
 
-
 __version__="0.0c"
 
 
 dkGen_debian_copyright () {
-	(test -n "$license" && ! test -r debian/copyright) && \
-		(mkdir -p debian; echo "$license" > debian/copyright) || true
+	if ! test -r $1/debian/copyright; then
+		if test -n "$license"; then echo "DK: Please define 'license'"; false; fi
+		if test -n "$DK_VERBOSE"; then echo "DK: Generating $1/debian/copyright"; fi
+		mkdir -p $1/debian; echo "$license" > $1/debian/copyright
+	fi
+}
+
+dkGen_debian_source_format () {
+	if ! test -r $1/debian/source/format; then
+		if test -n "$DK_VERBOSE"; then echo "DK: Generating $1/debian/source/format"; fi
+		mkdir -p $1/debian/source; echo "3.0 (quilt)" > $1/debian/source/format
+	fi
+}
+
+dkGen_debian_changelog () {
+	if ! test -r $1/debian/changelog; then
+		if test -n "$src"; then echo "DK: Please define 'src'"; false; fi
+		if test -n "$version"; then echo "DK: Please define 'version'"; false; fi
+		if test -n "$maintainer"; then echo "DK: Please define 'maintainer'"; false; fi
+		mkdir -p $1/debian
+		cat > $1/debian/changelog <<EOF
+$src ($version) experimental; urgency=low
+
+  * Unofficial D**ian User Repo Release.
+  * Built on $(uname -a)
+
+ -- $maintainer  $(date -R)
+EOF
+	fi
+}
+
+dkGen_debian_rules () {
+	if ! test -r $1/debian/rules; then
+		mkdir -p $1/debian
+		cat > $1/debian/rules <<EOF
+#!/usr/bin/make -f
+%:
+	dh $@
+EOF
+		chmod +x $1/debian/rules
+	fi
+}
+
+dkGen_SANITY_CHECK () {
+	# make sure the fundamental files are present
+	true
+}
+
+dkGenenerate () {
+	test -n "$1" || (echo "missing dest dir"; false)
+	dkGen_debian_copyright $1
+	dkGen_debian_source_format $1
+	dkGen_debian_changelog $1
+	dkGen_debian_rules $1
+	dkGen_SANITY_CHECK $1
 }
